#!/bin/bash
ln -s ~/.emacs.d/bash/.bash_profile ~/.bash_profile
ln -s ~/.emacs.d/bash/.bashrc ~/.bashrc
ln -s ~/.emacs.d/scripts/e /usr/local/bin/e
ln -s ~/.emacs.d/scripts/egui /usr/local/bin/egui
ln -s ~/.emacs.d/scripts/er /usr/local/bin/er
ln -s ~/.emacs.d/scripts/es /usr/local/bin/es

echo "[user]">> ~/.emacs.d/.git/config
echo "    name=cdtilde" >> ~/.emacs.d/.git/config
echo "    email=cdtilde@gmail.com" >> ~/.emacs.d/.git/config
